spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: "jdbc:mysql://localhost:3306/todo"
    #    url: "jdbc:mysql://localhost:3306/todo?useSSL=false"
    username: ralph
    password: ganymed$3

